  version: '3'
  services:
      database:
        image: mariadb:10.3
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: app_db
          MYSQL_USER: db_user
          MYSQL_PASSWORD: db_user_pass
        ports: [3306] 
        volumes:
          - ./database_mariadb_103:/var/lib/mysql
    
      phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
          - database
        environment:
          PMA_HOST: database
          PMA_PORT: 3306
          PMA_ARBITRARY: 1
        ports: [80]

      mailer:
        image: mailhog/mailhog
        ports: [1025, 8025]
